"use client";
import { useState, useEffect, useRef } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import UpgradeModal from "@/app/components/UpgradeModal";

interface Message {
  id: string;
  username: string;
  message: string;
  capturedAt: string;
}

interface Summary {
  bugs: string;
  uiUxIssues: string;
  featureRequests: string;
  positives: string;
  rawSummary: string;
  messageCount: number;
  actionableCount: number;
}

interface Props {
  session: {
    id: string;
    twitchChannel: string;
    status: string;
    autoStoppedReason?: string | null;
    startedAt: Date;
    game: { id: string; name: string; imageUrl: string | null };
    summary: Summary | null;
    _count: { messages: number };
  };
}

function parseSummaryField(val: string): string[] {
  try {
    return JSON.parse(val);
  } catch {
    return [];
  }
}

function generateMarkdown(
  channel: string,
  gameName: string,
  startedAt: Date,
  summary: Summary,
  bugs: string[],
  uiUxIssues: string[],
  featureRequests: string[],
  positives: string[],
): string {
  const date = new Date(startedAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const lines: string[] = [
    `# StreamSense Summary — ${gameName}`,
    ``,
    `**Channel:** #${channel}  `,
    `**Date:** ${date}  `,
    `**Messages captured:** ${summary.messageCount}  `,
    `**Actionable insights:** ${summary.actionableCount}`,
    ``,
    `---`,
    ``,
    `## Overview`,
    ``,
    summary.rawSummary,
    ``,
  ];
  if (bugs.length > 0) {
    lines.push(`## 🐛 Bugs & Glitches`, ``);
    bugs.forEach((b) => lines.push(`- ${b}`));
    lines.push(``);
  }
  if (uiUxIssues.length > 0) {
    lines.push(`## 🎮 UX & Controls`, ``);
    uiUxIssues.forEach((u) => lines.push(`- ${u}`));
    lines.push(``);
  }
  if (featureRequests.length > 0) {
    lines.push(`## ✨ Feature Requests`, ``);
    featureRequests.forEach((f) => lines.push(`- ${f}`));
    lines.push(``);
  }
  if (positives.length > 0) {
    lines.push(`## ❤️ What Players Loved`, ``);
    positives.forEach((p) => lines.push(`- ${p}`));
    lines.push(``);
  }
  lines.push(`---`);
  lines.push(`*Generated by StreamSense*`);
  return lines.join("\n");
}

export default function SessionLiveView({ session }: Props) {
  const [messages, setMessages] = useState<Message[]>([]);
  const [status, setStatus] = useState(session.status);
  const [summary, setSummary] = useState<Summary | null>(session.summary);
  const [summarizing, setSummarizing] = useState(false);
  const lastIdRef = useRef<string | undefined>(undefined);
  const bottomRef = useRef<HTMLDivElement>(null);
  const router = useRouter();
  const [deleting, setDeleting] = useState(false);
  const [limitError, setLimitError] = useState<string | null>(null);
  const [usageInfo, setUsageInfo] = useState<{
    usedTotal: number;
    limit: number;
    remaining: number;
    isPro: boolean;
  } | null>(null);
  const [showUpgrade, setShowUpgrade] = useState(false);

  useEffect(() => {
    if (status !== "ACTIVE") return;
    async function fetchMessages() {
      const url = `/api/sessions/${session.id}/messages${lastIdRef.current ? `?after=${lastIdRef.current}` : ""}`;
      const res = await fetch(url);
      if (!res.ok) return;
      const data = await res.json();
      if (data.messages?.length > 0) {
        setMessages((prev) => {
          const existingIds = new Set(prev.map((m) => m.id));
          return [
            ...prev,
            ...data.messages.filter((m: Message) => !existingIds.has(m.id)),
          ];
        });
        lastIdRef.current = data.messages[data.messages.length - 1].id;
      }
      if (data.status !== "ACTIVE") {
        setStatus(data.status);
        if (data.summary) setSummary(data.summary);
      }
    }
    fetchMessages();
    const interval = setInterval(fetchMessages, 3000);
    return () => clearInterval(interval);
  }, [session.id, status]);

  useEffect(() => {
    if (status !== "ACTIVE") {
      fetch(`/api/sessions/${session.id}/messages`)
        .then((r) => r.json())
        .then((data) => {
          if (data.messages) {
            setMessages((prev) => {
              const existingIds = new Set(prev.map((m) => m.id));
              return [
                ...prev,
                ...data.messages.filter((m: Message) => !existingIds.has(m.id)),
              ];
            });
          }
          if (data.summary) setSummary(data.summary);
        });
    }
  }, []);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  useEffect(() => {
    fetch("/api/sessions/usage")
      .then((r) => r.json())
      .then((data) => {
        setUsageInfo({
          usedTotal: data.usedTotal,
          limit: data.limit,
          remaining: data.remaining,
          isPro: data.isPro,
        });
      });
  }, []);

  async function handleStop() {
    setSummarizing(true);
    setLimitError(null);
    const res = await fetch(`/api/sessions/${session.id}`, { method: "PATCH" });
    if (!res.ok) {
      setLimitError("Failed to stop session. Try again.");
      setSummarizing(false);
      return;
    }
    setStatus("COMPLETED");
    setSummarizing(false);
  }

  async function handleSummarize() {
    setSummarizing(true);
    setLimitError(null);
    try {
      const res = await fetch(`/api/sessions/${session.id}/summarize`, {
        method: "POST",
      });
      if (res.status === 429) {
        setSummarizing(false);
        setShowUpgrade(true);
        return;
      }
      const interval = setInterval(async () => {
        const r = await fetch(`/api/sessions/${session.id}/messages`);
        const d = await r.json();
        if (d.summary) {
          setSummary(d.summary);
          setSummarizing(false);
          clearInterval(interval);
        }
      }, 2000);
    } catch {
      setLimitError("Something went wrong. Try again.");
      setSummarizing(false);
    }
  }

  async function handleDelete() {
    if (
      !confirm(
        "Delete this session and all its messages? This cannot be undone.",
      )
    )
      return;
    setDeleting(true);
    await fetch(`/api/sessions/${session.id}`, { method: "DELETE" });
    router.push(`/sessions?game=${session.game.id}`);
  }

  function handleExportMarkdown() {
    if (!summary) return;
    const md = generateMarkdown(
      session.twitchChannel,
      session.game.name,
      session.startedAt,
      summary,
      bugs,
      uiUxIssues,
      featureRequests,
      positives,
    );
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `streamsense-${session.game.name.toLowerCase().replace(/\s+/g, "-")}-${session.twitchChannel}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function handleExportPDF() {
    if (!summary) return;
    const date = new Date(session.startedAt).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
    const sectionHtml = (title: string, color: string, items: string[]) =>
      items.length === 0
        ? ""
        : `<div class="section"><h3 style="color:${color}">${title}</h3><ul>${items.map((i) => `<li>${i}</li>`).join("")}</ul></div>`;
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>StreamSense — ${session.game.name}</title><style>body{font-family:Georgia,serif;max-width:720px;margin:40px auto;color:#111;line-height:1.6}h1{font-size:1.8rem;margin-bottom:4px}.meta{color:#666;font-size:.9rem;margin-bottom:24px}.overview{background:#f9f9f9;border-left:4px solid #f0a500;padding:16px 20px;border-radius:4px;margin-bottom:24px}.stats{display:flex;gap:32px;margin-bottom:24px}.stat{text-align:center}.stat-value{font-size:2rem;font-weight:bold;color:#f0a500;font-family:monospace}.stat-label{font-size:.8rem;color:#666}.section{margin-bottom:24px}.section h3{font-size:1rem;text-transform:uppercase;letter-spacing:.05em;margin-bottom:8px}ul{padding-left:20px;margin:0}li{margin-bottom:4px}.footer{margin-top:40px;padding-top:16px;border-top:1px solid #eee;font-size:.8rem;color:#999}@media print{body{margin:20px}}</style></head><body><h1>${session.game.name}</h1><div class="meta">#${session.twitchChannel} &nbsp;·&nbsp; ${date}</div><div class="stats"><div class="stat"><div class="stat-value">${summary.messageCount}</div><div class="stat-label">messages</div></div><div class="stat"><div class="stat-value">${summary.actionableCount}</div><div class="stat-label">actionable</div></div></div><div class="overview">${summary.rawSummary}</div>${sectionHtml("🐛 Bugs & Glitches", "#ff4d6a", bugs)}${sectionHtml("🎮 UX & Controls", "#4d9fff", uiUxIssues)}${sectionHtml("✨ Feature Requests", "#f0a500", featureRequests)}${sectionHtml("❤️ What Players Loved", "#3effa0", positives)}<div class="footer">Generated by StreamSense</div></body></html>`;
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 500);
  }

  const bugs = summary ? parseSummaryField(summary.bugs) : [];
  const uiUxIssues = summary ? parseSummaryField(summary.uiUxIssues) : [];
  const featureRequests = summary
    ? parseSummaryField(summary.featureRequests)
    : [];
  const positives = summary ? parseSummaryField(summary.positives) : [];

  return (
    <div className="slv-root">
      <style>{`
        .slv-root {
          height: 100vh;
          display: flex;
          flex-direction: column;
          overflow: hidden;
        }
        .slv-header {
          border-bottom: 1px solid var(--border);
          padding: 14px 32px;
          display: flex;
          align-items: center;
          justify-content: space-between;
          flex-shrink: 0;
          gap: 12px;
          flex-wrap: wrap;
        }
        .slv-breadcrumb {
          display: flex;
          align-items: center;
          gap: 6px;
          min-width: 0;
          overflow: hidden;
        }
        .slv-breadcrumb-game {
          display: inline;
        }
        .slv-header-right {
          display: flex;
          align-items: center;
          gap: 10px;
          flex-shrink: 0;
        }
        .slv-usage {
          display: inline;
        }
        .slv-grid {
          flex: 1;
          display: grid;
          grid-template-columns: 1fr 380px;
          overflow: hidden;
          height: 100%;
        }
        .slv-grid-single {
          flex: 1;
          display: grid;
          grid-template-columns: 1fr;
          overflow: hidden;
          height: 100%;
        }
        .slv-summary-panel {
          overflow-y: auto;
          padding: 24px;
          border-left: 1px solid var(--border);
        }
        @media (max-width: 768px) {
          .slv-root {
            height: auto;
            min-height: 100vh;
            overflow: auto;
          }
          .slv-header {
            padding: 12px 16px;
          }
          .slv-breadcrumb-game {
            display: none;
          }
          .slv-usage {
            display: none;
          }
          .slv-header-right {
            gap: 8px;
          }
          .slv-grid, .slv-grid-single {
            display: flex;
            flex-direction: column;
            height: auto;
            overflow: visible;
          }
          .slv-summary-panel {
            border-left: none;
            border-top: 1px solid var(--border);
            padding: 16px;
          }
        }
        .slv-chat-feed {
          display: flex;
          flex-direction: column;
          overflow: hidden;
          height: 100%;
        }
        .slv-messages {
          flex: 1;
          overflow-y: auto;
          padding: 16px 20px;
          display: flex;
          flex-direction: column;
          gap: 6px;
          min-height: 0;
        }
        @media (max-width: 768px) {
          .slv-chat-feed {
            height: 60vh;
            min-height: 300px;
          }
          .slv-messages {
            flex: 1;
          }
          .slv-stop-btn span.slv-btn-label-long { display: none; }
          .slv-stop-btn span.slv-btn-label-short { display: inline; }
          .slv-delete-btn span.slv-btn-label-long { display: none; }
          .slv-delete-btn span.slv-btn-label-short { display: inline; }
        }
        @media (min-width: 769px) {
          .slv-stop-btn span.slv-btn-label-short { display: none; }
          .slv-delete-btn span.slv-btn-label-short { display: none; }
        }
      `}</style>

      {showUpgrade && <UpgradeModal onClose={() => setShowUpgrade(false)} />}

      {/* Header */}
      <header className="slv-header">
        <div className="slv-breadcrumb">
          <Link
            href="/"
            style={{
              fontFamily: "'Space Mono', monospace",
              fontWeight: 700,
              color: "var(--text)",
              textDecoration: "none",
              whiteSpace: "nowrap",
            }}
          >
            StreamSense
          </Link>
          <span style={{ color: "var(--text-dim)" }}>/</span>
          <Link
            href="/dashboard"
            style={{
              color: "var(--text-muted)",
              fontSize: "0.85rem",
              textDecoration: "none",
              whiteSpace: "nowrap",
            }}
          >
            Dashboard
          </Link>
          <span
            className="slv-breadcrumb-game"
            style={{ color: "var(--text-dim)" }}
          >
            /
          </span>
          <Link
            className="slv-breadcrumb-game"
            href={`/sessions?game=${session.game.id}`}
            style={{
              color: "var(--text-muted)",
              fontSize: "0.85rem",
              textDecoration: "none",
              overflow: "hidden",
              textOverflow: "ellipsis",
              whiteSpace: "nowrap",
              maxWidth: 120,
            }}
          >
            {session.game.name}
          </Link>
          <span style={{ color: "var(--text-dim)" }}>/</span>
          <span
            className="mono"
            style={{
              color: "var(--text)",
              fontSize: "0.85rem",
              whiteSpace: "nowrap",
            }}
          >
            #{session.twitchChannel}
          </span>
        </div>

        <div className="slv-header-right">
          <span
            className="mono slv-usage"
            style={{
              fontSize: "0.72rem",
              color:
                usageInfo?.remaining === 0
                  ? "var(--red)"
                  : usageInfo?.remaining === 1
                    ? "var(--accent)"
                    : "var(--text-muted)",
            }}
          >
            {usageInfo &&
              !usageInfo.isPro &&
              status !== "COMPLETED" &&
              `${usageInfo.remaining}/${usageInfo.limit} left`}
          </span>

          <span
            className="badge"
            style={{
              background:
                status === "COMPLETED"
                  ? "var(--green-dim)"
                  : status === "ACTIVE"
                    ? "var(--accent-dim)"
                    : "var(--red-dim)",
              color:
                status === "COMPLETED"
                  ? "var(--green)"
                  : status === "ACTIVE"
                    ? "var(--accent)"
                    : "var(--red)",
              border: `1px solid ${status === "COMPLETED" ? "rgba(62,255,160,0.15)" : status === "ACTIVE" ? "var(--accent-border)" : "rgba(255,77,106,0.2)"}`,
              display: "flex",
              alignItems: "center",
              gap: 6,
              whiteSpace: "nowrap",
            }}
          >
            {status === "ACTIVE" && (
              <span
                className="pulse-dot"
                style={{
                  display: "inline-block",
                  width: 6,
                  height: 6,
                  borderRadius: "50%",
                  background: "var(--accent)",
                }}
              />
            )}
            {status === "ACTIVE"
              ? "Live"
              : status.charAt(0) + status.slice(1).toLowerCase()}
          </span>

          {status === "ACTIVE" && (
            <button
              className="slv-stop-btn"
              onClick={handleStop}
              disabled={summarizing}
              style={{
                padding: "8px 14px",
                background: "var(--red)",
                color: "#fff",
                border: "none",
                borderRadius: 8,
                fontWeight: 700,
                fontSize: "0.82rem",
                cursor: "pointer",
                fontFamily: "'Space Mono', monospace",
                opacity: summarizing ? 0.6 : 1,
                whiteSpace: "nowrap",
              }}
            >
              <span className="slv-btn-label-long">
                {summarizing ? "Stopping..." : "Stop & Summarize"}
              </span>
              <span className="slv-btn-label-short">
                {summarizing ? "..." : "Stop"}
              </span>
            </button>
          )}

          {status === "COMPLETED" && (
            <button
              className="slv-delete-btn"
              onClick={handleDelete}
              disabled={deleting}
              style={{
                padding: "8px 14px",
                background: "transparent",
                color: "var(--text-muted)",
                border: "1px solid var(--border)",
                borderRadius: 8,
                fontWeight: 600,
                fontSize: "0.82rem",
                cursor: "pointer",
                fontFamily: "'Space Mono', monospace",
                opacity: deleting ? 0.6 : 1,
                whiteSpace: "nowrap",
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.borderColor = "var(--red)";
                e.currentTarget.style.color = "var(--red)";
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.borderColor = "var(--border)";
                e.currentTarget.style.color = "var(--text-muted)";
              }}
            >
              <span className="slv-btn-label-long">
                {deleting ? "Deleting..." : "Delete Session"}
              </span>
              <span className="slv-btn-label-short">
                {deleting ? "..." : "Delete"}
              </span>
            </button>
          )}
        </div>
      </header>

      {/* Auto-stop notice */}
      {session.autoStoppedReason && status === "COMPLETED" && (
        <div
          style={{
            padding: "10px 20px",
            background: "var(--accent-dim)",
            borderBottom: "1px solid var(--accent-border)",
            fontSize: "0.82rem",
            color: "var(--accent)",
            flexShrink: 0,
            display: "flex",
            alignItems: "center",
            gap: 8,
          }}
        >
          <span>⚡</span>
          <span>
            Session auto-stopped: <strong>{session.autoStoppedReason}</strong>
          </span>
        </div>
      )}

      {limitError && (
        <div
          style={{
            padding: "12px 20px",
            background: "var(--red-dim)",
            borderBottom: "1px solid rgba(255,77,106,0.2)",
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            flexShrink: 0,
          }}
        >
          <span style={{ fontSize: "0.85rem", color: "var(--red)" }}>
            ⚠ {limitError}
          </span>
          <button
            onClick={() => setLimitError(null)}
            style={{
              background: "none",
              border: "none",
              color: "var(--red)",
              cursor: "pointer",
              fontSize: "1rem",
              padding: 0,
            }}
          >
            ✕
          </button>
        </div>
      )}

      {/* Main content */}
      <div
        className={
          status === "COMPLETED" && summary ? "slv-grid" : "slv-grid-single"
        }
      >
        {/* Chat feed */}
        <div className="slv-chat-feed">
          <div
            style={{
              padding: "12px 20px",
              borderBottom: "1px solid var(--border)",
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              flexShrink: 0,
            }}
          >
            <span
              className="mono"
              style={{ fontSize: "0.72rem", color: "var(--text-muted)" }}
            >
              Showing {messages.length} messages
            </span>
            {status === "ACTIVE" && (
              <span
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 6,
                  fontSize: "0.72rem",
                  color: "var(--text-muted)",
                }}
              >
                <span
                  className="pulse-dot"
                  style={{
                    display: "inline-block",
                    width: 5,
                    height: 5,
                    borderRadius: "50%",
                    background: "var(--green)",
                  }}
                />
                collecting
              </span>
            )}
          </div>
          <div className="slv-messages">
            {messages.length === 0 && status === "ACTIVE" && (
              <div
                style={{
                  textAlign: "center",
                  color: "var(--text-dim)",
                  fontSize: "0.85rem",
                  marginTop: 48,
                }}
              >
                <div style={{ fontSize: 24, marginBottom: 12 }}>⏳</div>
                Waiting for chat messages...
                <br />
                <span style={{ fontSize: "0.75rem" }}>
                  Make sure the worker is running in a separate terminal
                </span>
              </div>
            )}
            {messages.map((msg) => (
              <div
                key={msg.id}
                style={{ display: "flex", gap: 10, alignItems: "baseline" }}
              >
                <span
                  className="mono"
                  style={{
                    fontSize: "0.72rem",
                    color: "var(--accent)",
                    fontWeight: 700,
                    flexShrink: 0,
                  }}
                >
                  {msg.username}
                </span>
                <span
                  style={{
                    fontSize: "0.85rem",
                    color: "var(--text-muted)",
                    lineHeight: 1.5,
                  }}
                >
                  {msg.message}
                </span>
              </div>
            ))}
            <div ref={bottomRef} />
          </div>
        </div>

        {/* Summary panel */}
        {status === "COMPLETED" && summary && (
          <div className="slv-summary-panel">
            <div style={{ marginBottom: 20 }}>
              <div
                className="mono"
                style={{
                  fontSize: "0.7rem",
                  color: "var(--text-muted)",
                  textTransform: "uppercase",
                  letterSpacing: "0.1em",
                  marginBottom: 8,
                }}
              >
                AI Summary
              </div>
              <p
                style={{
                  fontSize: "0.85rem",
                  color: "var(--text-muted)",
                  lineHeight: 1.65,
                  margin: 0,
                }}
              >
                {summary.rawSummary}
              </p>
            </div>
            <div style={{ display: "flex", gap: 12, marginBottom: 20 }}>
              <div
                className="card"
                style={{ padding: "12px 16px", flex: 1, textAlign: "center" }}
              >
                <div
                  className="mono"
                  style={{
                    fontSize: "1.3rem",
                    fontWeight: 700,
                    color: "var(--accent)",
                  }}
                >
                  {summary.actionableCount}
                </div>
                <div
                  style={{ fontSize: "0.68rem", color: "var(--text-muted)" }}
                >
                  actionable
                </div>
              </div>
              <div
                className="card"
                style={{ padding: "12px 16px", flex: 1, textAlign: "center" }}
              >
                <div
                  className="mono"
                  style={{ fontSize: "1.3rem", fontWeight: 700 }}
                >
                  {summary.messageCount}
                </div>
                <div
                  style={{ fontSize: "0.68rem", color: "var(--text-muted)" }}
                >
                  messages
                </div>
              </div>
            </div>
            {[
              {
                label: "Bugs",
                items: bugs,
                color: "var(--red)",
                bg: "var(--red-dim)",
              },
              {
                label: "UX Issues",
                items: uiUxIssues,
                color: "var(--blue)",
                bg: "var(--blue-dim)",
              },
              {
                label: "Feature Requests",
                items: featureRequests,
                color: "var(--accent)",
                bg: "var(--accent-dim)",
              },
              {
                label: "What Players Loved",
                items: positives,
                color: "var(--green)",
                bg: "var(--green-dim)",
              },
            ].map((section) =>
              section.items.length > 0 ? (
                <div key={section.label} style={{ marginBottom: 20 }}>
                  <div
                    className="badge"
                    style={{
                      background: section.bg,
                      color: section.color,
                      display: "inline-block",
                      marginBottom: 10,
                    }}
                  >
                    {section.label}
                  </div>
                  <div
                    style={{ display: "flex", flexDirection: "column", gap: 6 }}
                  >
                    {section.items.map((item, i) => (
                      <div
                        key={i}
                        style={{
                          display: "flex",
                          gap: 8,
                          alignItems: "flex-start",
                          fontSize: "0.82rem",
                          color: "var(--text-muted)",
                          lineHeight: 1.5,
                        }}
                      >
                        <span
                          style={{
                            color: section.color,
                            flexShrink: 0,
                            marginTop: 1,
                          }}
                        >
                          ›
                        </span>
                        {item}
                      </div>
                    ))}
                  </div>
                </div>
              ) : null,
            )}
            {/* Export */}
            <div style={{ marginTop: 24 }}>
              <div
                className="mono"
                style={{
                  fontSize: "0.7rem",
                  color: "var(--accent)",
                  textTransform: "uppercase",
                  letterSpacing: "0.1em",
                  marginBottom: 10,
                }}
              >
                Save your summary
              </div>
              <div style={{ display: "flex", gap: 8 }}>
                {[
                  { label: "↓ Markdown", handler: handleExportMarkdown },
                  { label: "↓ PDF", handler: handleExportPDF },
                ].map(({ label, handler }) => (
                  <button
                    key={label}
                    onClick={handler}
                    style={{
                      flex: 1,
                      padding: "9px 12px",
                      background: "transparent",
                      border: "1px solid var(--border)",
                      borderRadius: 8,
                      color: "var(--text-muted)",
                      cursor: "pointer",
                      fontSize: "0.78rem",
                      fontFamily: "'Space Mono', monospace",
                      fontWeight: 600,
                      transition: "border-color 0.2s, color 0.2s",
                    }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.borderColor = "var(--accent)";
                      e.currentTarget.style.color = "var(--accent)";
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.borderColor = "var(--border)";
                      e.currentTarget.style.color = "var(--text-muted)";
                    }}
                  >
                    {label}
                  </button>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* Waiting for summary */}
        {status === "COMPLETED" && !summary && (
          <div
            style={{
              padding: 24,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              flexDirection: "column",
              gap: 12,
              color: "var(--text-muted)",
            }}
          >
            {usageInfo?.remaining === 0 && !usageInfo?.isPro ? (
              <>
                <div style={{ fontSize: 24 }}>⚡</div>
                <p
                  style={{
                    fontSize: "0.85rem",
                    textAlign: "center",
                    margin: 0,
                  }}
                >
                  You've used all your free summaries.
                </p>
                <button
                  onClick={() => setShowUpgrade(true)}
                  style={{
                    padding: "10px 24px",
                    background: "var(--accent)",
                    color: "#000",
                    border: "none",
                    borderRadius: 8,
                    fontWeight: 700,
                    fontSize: "0.88rem",
                    cursor: "pointer",
                    fontFamily: "'Space Mono', monospace",
                  }}
                >
                  Upgrade to Pro →
                </button>
              </>
            ) : (
              <>
                <p
                  style={{
                    fontSize: "0.85rem",
                    textAlign: "center",
                    margin: 0,
                  }}
                >
                  Session complete — ready to summarize.
                </p>
                <p
                  style={{
                    fontSize: "0.78rem",
                    textAlign: "center",
                    color: "var(--text-dim)",
                    margin: 0,
                  }}
                >
                  {usageInfo &&
                    !usageInfo.isPro &&
                    `${usageInfo.remaining} of ${usageInfo.limit} free summaries remaining`}
                </p>
                <button
                  onClick={handleSummarize}
                  disabled={summarizing}
                  style={{
                    padding: "10px 24px",
                    background: "var(--accent)",
                    color: "#000",
                    border: "none",
                    borderRadius: 8,
                    fontWeight: 700,
                    fontSize: "0.88rem",
                    cursor: summarizing ? "not-allowed" : "pointer",
                    fontFamily: "'Space Mono', monospace",
                    opacity: summarizing ? 0.6 : 1,
                  }}
                >
                  {summarizing ? "Generating..." : "Summarize Session"}
                </button>
              </>
            )}
            {limitError && (
              <p
                style={{
                  fontSize: "0.82rem",
                  color: "var(--red)",
                  margin: 0,
                  textAlign: "center",
                }}
              >
                {limitError}
              </p>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
